-- Ejecutar para permitir crear funciones
SET GLOBAL log_bin_trust_function_creators = 1;

CREATE TABLE clientes (
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NULL,
DIRECCION VARCHAR(150) ,
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(10),
CP VARCHAR(10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT,
PRIMARY KEY(DNI)
);

SELECT * FROM clientes;

SELECT * FROM vendedores;

CREATE TABLE productos (
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCCION VARCHAR(100),
SABOR VARCHAR(50),
TAMANO VARCHAR(50),
ENVASE VARCHAR(50),
PRECIO FLOAT,
PRIMARY KEY(CODIGO)
);
