CREATE DATABASE jugos_ventas;

INSERT INTO items 
SELECT NUMERO, CODIGO_DEL_PRODUCTO AS CODIGO, CANTIDAD, PRECIO 
FROM jugos_ventas.items_facturas;

INSERT INTO facturas
SELECT NUMERO, FECHA_VENTA AS FECHA, DNI, MATRICULA, IMPUESTO
FROM jugos_ventas.facturas;

-- CASE SENSITIVE PARA PROCEDIMIENTOS ALMACENADOS Y FUNCIONES

SELECT * FROM facturas F
INNER JOIN items I
ON F.NUMERO = I.NUMERO;

SELECT * FROM items;